import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Oxanium } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import QueryProvider from "@/providers/query-client";
import { Toaster } from "@/components/ui/sonner";


const oxaniumHeading = Oxanium({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
        oxaniumHeading.variable,
      )}
    >
      <body className="flex flex-col min-h-full">
        <QueryProvider>
          <TooltipProvider>
            {children}
            <Toaster position="top-right"/>

          </TooltipProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
